version: "3.8"

services: 
  db:
    image: timescale/timescaledb:2.0.0-pg12
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=savtrik

  backend:
    build: .
    volumes:
      - .:/app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports: 
      - "8000:8000"
    depends_on: 
      - db

  pg-admin:
    image: dpage/pgadmin4:latest
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@savtrik.com"
      PGADMIN_DEFAULT_PASSWORD: "savtrik123"
    ports: 
      - "5050:80"
    depends_on:
      - db