version: "3"
services:
  demo-container-db:
    image: timescale/timescaledb:2.0.0-pg12
    environment:
      POSTGRES_USER: savtrik
      POSTGRES_PASSWORD: 2345678910Aa
      POSTGRES_DATABASE: my_database
    ports:
      - "5432:5432"
    networks:
      - savtrik_network
    volumes:
      - db-data:/var/lib/postgresql/data
  demo-pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: savtrik@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8888:80"
    networks:
      - savtrik_network
    
networks:
  savtrik_network:
    driver: bridge
  
volumes:
  db-data: